# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_default: dark

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'Consultant'
    org_name: 'Allianz'
    description: 'Economist / Data Scientist'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: floating-theme-toggler

# Site footer
footer:
  copyright:
    notice: '© {year} Nikhil Sebastian'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
